#!/usr/bin/env python3
"""Combine ui/index.html + ui/app.js into a single self-contained HTML
document and emit it as a C++ raw-string header (src/ui_html.h)."""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
html_path = os.path.join(ROOT, "ui", "index.html")
js_path   = os.path.join(ROOT, "ui", "app.js")
out_path  = os.path.join(ROOT, "src", "ui_html.h")

with open(html_path, "r", encoding="utf-8") as f:
    html = f.read()
with open(js_path, "r", encoding="utf-8") as f:
    js = f.read()

# Inline the external script tag with the actual JS so the document is fully self-contained.
inlined = html.replace(
    '<script src="app.js"></script>',
    "<script>\n" + js + "\n</script>"
)

# Pick a raw-string delimiter that does not collide with the content.
delim = "UIHTML"
while (')' + delim + '"') in inlined:
    delim += "X"

header = (
    "// AUTO-GENERATED by tools/embed.py — do not edit by hand.\n"
    "// Contains the entire NetSaver UI (HTML+CSS+JS) as one string.\n"
    "#ifndef NETSAVER_UI_HTML_H\n"
    "#define NETSAVER_UI_HTML_H\n\n"
    "static const char* UI_HTML = R\"" + delim + "(" + inlined + ")" + delim + "\";\n\n"
    "#endif // NETSAVER_UI_HTML_H\n"
)

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(header)

print("Wrote %s (%d bytes embedded)" % (out_path, len(inlined)))
