// ============================================================
//  NetSaver — native Windows shell (WebView2 + embedded UI)
//
//  - Embeds the full HTML/CSS/JS UI (see ui_html.h, generated by
//    tools/embed.py) and renders it inside a borderless-capable
//    WebView2 window.
//  - Provides a JS<->C++ bridge so the web UI can persist data to a
//    real file next to the executable (true auto-save that survives
//    restarts) and export/import backups via native file dialogs.
// ============================================================
#define WIN32_LEAN_AND_MEAN
#define UNICODE
#define _UNICODE

#include <windows.h>
#include <shlobj.h>
#include <commdlg.h>
#include <string>
#include <cstdio>
#include <vector>

#include "webview.h"
#include "ui_html.h"

// ---------- small UTF-8 <-> UTF-16 helpers ----------
static std::wstring widen(const std::string& s) {
    if (s.empty()) return L"";
    int n = MultiByteToWideChar(CP_UTF8, 0, s.c_str(), (int)s.size(), nullptr, 0);
    std::wstring w(n, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, s.c_str(), (int)s.size(), &w[0], n);
    return w;
}
static std::string narrow(const std::wstring& w) {
    if (w.empty()) return "";
    int n = WideCharToMultiByte(CP_UTF8, 0, w.c_str(), (int)w.size(), nullptr, 0, nullptr, nullptr);
    std::string s(n, '\0');
    WideCharToMultiByte(CP_UTF8, 0, w.c_str(), (int)w.size(), &s[0], n, nullptr, nullptr);
    return s;
}

// ---------- where to store the data file ----------
// Prefer %APPDATA%\NetSaver\netsaver_data.json so it is writable even when the
// EXE lives in Program Files / a read-only folder.
static std::wstring dataDir() {
    std::wstring dir;
    wchar_t appdata[MAX_PATH];
    if (SUCCEEDED(SHGetFolderPathW(nullptr, CSIDL_APPDATA, nullptr, 0, appdata))) {
        dir = appdata;
        dir += L"\\NetSaver";
        CreateDirectoryW(dir.c_str(), nullptr);
    } else {
        wchar_t buf[MAX_PATH]; GetCurrentDirectoryW(MAX_PATH, buf); dir = buf;
    }
    return dir;
}
static std::wstring dataFile() { return dataDir() + L"\\netsaver_data.json"; }

static std::string readFileUtf8(const std::wstring& path) {
    FILE* f = _wfopen(path.c_str(), L"rb");
    if (!f) return "";
    std::string out;
    char buf[8192]; size_t n;
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) out.append(buf, n);
    fclose(f);
    return out;
}
// Atomic, single-file save: write to "<path>.tmp" then replace the real file
// in place. This guarantees there is always exactly ONE data file and it is
// never left half-written, even if the app is closed mid-save. No backup
// copies / history files are ever created, so disk + memory usage stay flat.
static bool writeFileUtf8(const std::wstring& path, const std::string& content) {
    std::wstring tmp = path + L".tmp";
    FILE* f = _wfopen(tmp.c_str(), L"wb");
    if (!f) return false;
    size_t w = fwrite(content.data(), 1, content.size(), f);
    fflush(f);
    fclose(f);
    if (w != content.size()) { _wremove(tmp.c_str()); return false; }
    // Replace existing file atomically (falls back to remove+rename if needed).
    if (!MoveFileExW(tmp.c_str(), path.c_str(), MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        _wremove(path.c_str());
        if (!MoveFileExW(tmp.c_str(), path.c_str(), MOVEFILE_REPLACE_EXISTING)) {
            _wremove(tmp.c_str());
            return false;
        }
    }
    return true;
}

// ---------- JSON string helpers for bridge replies ----------
// The webview bind() callback receives a JSON array string of the JS args, e.g.
// '["<json text>"]'. We return a JSON-encoded result string.
static std::string jsonEscape(const std::string& s) {
    std::string o; o.reserve(s.size() + 16);
    for (char c : s) {
        switch (c) {
            case '"':  o += "\\\""; break;
            case '\\': o += "\\\\"; break;
            case '\n': o += "\\n";  break;
            case '\r': o += "\\r";  break;
            case '\t': o += "\\t";  break;
            case '\b': o += "\\b";  break;
            case '\f': o += "\\f";  break;
            default:
                if ((unsigned char)c < 0x20) {
                    char buf[8]; sprintf(buf, "\\u%04x", c); o += buf;
                } else o += c;
        }
    }
    return o;
}

// Minimal JSON parser to pull the first string element out of an args array
// like ["...."] or ["a","b"]. Returns decoded UTF-8 strings.
static std::vector<std::string> parseArgArray(const std::string& req) {
    std::vector<std::string> out;
    size_t i = 0, n = req.size();
    while (i < n && req[i] != '[') i++;
    if (i < n) i++; // skip '['
    while (i < n) {
        while (i < n && (req[i] == ' ' || req[i] == ',' )) i++;
        if (i < n && req[i] == ']') break;
        if (i < n && req[i] == '"') {
            i++; std::string s;
            while (i < n && req[i] != '"') {
                char c = req[i];
                if (c == '\\' && i + 1 < n) {
                    char e = req[i+1]; i += 2;
                    switch (e) {
                        case 'n': s += '\n'; break;
                        case 'r': s += '\r'; break;
                        case 't': s += '\t'; break;
                        case 'b': s += '\b'; break;
                        case 'f': s += '\f'; break;
                        case '"': s += '"';  break;
                        case '\\': s += '\\'; break;
                        case '/': s += '/';  break;
                        case 'u': {
                            if (i + 4 <= n) {
                                std::string hex = req.substr(i, 4); i += 4;
                                unsigned int cp = (unsigned int)strtol(hex.c_str(), nullptr, 16);
                                // encode UTF-8
                                if (cp < 0x80) s += (char)cp;
                                else if (cp < 0x800) { s += (char)(0xC0|(cp>>6)); s += (char)(0x80|(cp&0x3F)); }
                                else { s += (char)(0xE0|(cp>>12)); s += (char)(0x80|((cp>>6)&0x3F)); s += (char)(0x80|(cp&0x3F)); }
                            }
                            break;
                        }
                        default: s += e;
                    }
                } else { s += c; i++; }
            }
            if (i < n) i++; // closing quote
            out.push_back(s);
        } else {
            // skip non-string token (number/bool/null)
            while (i < n && req[i] != ',' && req[i] != ']') i++;
        }
    }
    return out;
}

// ---------- native file dialogs ----------
static std::wstring saveFileDialog(const std::wstring& suggested) {
    wchar_t file[MAX_PATH]; wcsncpy(file, suggested.c_str(), MAX_PATH); file[MAX_PATH-1]=0;
    OPENFILENAMEW ofn = {0};
    ofn.lStructSize = sizeof(ofn);
    ofn.lpstrFilter = L"JSON Backup (*.json)\0*.json\0All Files\0*.*\0";
    ofn.lpstrFile = file; ofn.nMaxFile = MAX_PATH;
    ofn.lpstrDefExt = L"json";
    ofn.Flags = OFN_OVERWRITEPROMPT | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;
    if (GetSaveFileNameW(&ofn)) return file;
    return L"";
}

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE, LPSTR, int) {
    // Keep WebView2's footprint small: cap the disk cache and disable extra
    // background features so auto-save / browsing don't pile up cache on disk
    // or hold excess memory. WebView2 reads these env vars at startup.
    SetEnvironmentVariableW(L"WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS",
        L"--disk-cache-size=10485760 --disable-features=msWebOOUI,msPdfOOUI "
        L"--disable-background-networking --disable-component-update");
    // Pin the WebView2 user-data folder next to our own data so it can be
    // cleared predictably and never scatters cache elsewhere.
    SetEnvironmentVariableW(L"WEBVIEW2_USER_DATA_FOLDER", dataDir().c_str());

    // WebView2/CoInitialize handled by the library. debug=false keeps DevTools
    // off and the renderer lean in the shipped build.
    webview::webview w(false, nullptr);
    w.set_title("NetSaver — Site & Account Vault");

    // Apply the embedded application icon to the native window.
    {
        HWND hwnd = (HWND)w.window();
        if (hwnd) {
            HICON hIcon = (HICON)LoadImageW(hInst, MAKEINTRESOURCEW(101), IMAGE_ICON,
                                            0, 0, LR_DEFAULTSIZE | LR_SHARED);
            if (hIcon) {
                SendMessageW(hwnd, WM_SETICON, ICON_BIG,   (LPARAM)hIcon);
                SendMessageW(hwnd, WM_SETICON, ICON_SMALL, (LPARAM)hIcon);
            }
        }
    }
    w.set_size(1280, 820, WEBVIEW_HINT_NONE);
    w.set_size(720, 480, WEBVIEW_HINT_MIN);

    // ---- bind: loadData() -> returns stored JSON string (or "null") ----
    w.bind("loadData", [](const std::string& /*req*/) -> std::string {
        std::string data = readFileUtf8(dataFile());
        if (data.empty()) return "null";
        return "\"" + jsonEscape(data) + "\"";
    });

    // ---- bind: saveData(jsonString) -> "true"/"false" ----
    w.bind("saveData", [](const std::string& req) -> std::string {
        auto args = parseArgArray(req);
        if (args.empty()) return "false";
        bool ok = writeFileUtf8(dataFile(), args[0]);
        return ok ? "true" : "false";
    });

    // ---- bind: exportBackup(filename, jsonString) -> writes via Save dialog ----
    w.bind("exportBackup", [](const std::string& req) -> std::string {
        auto args = parseArgArray(req);
        if (args.size() < 2) return "false";
        std::wstring suggested = widen(args[0]);
        std::wstring path = saveFileDialog(suggested);
        if (path.empty()) return "false";
        bool ok = writeFileUtf8(path, args[1]);
        return ok ? "true" : "false";
    });

    // Load the embedded UI directly (everything ships inside this one EXE).
    // NavigateToString comfortably handles documents up to ~2 MB; ours is ~50 KB.
    w.set_html(UI_HTML);

    w.run();
    return 0;
}
